### ISSUE TITLE
Files don't load

### ISSUE THREAD

**Issue by Sembiance** [martenjj/drawview#5]
I've encountered a few Acorn Draw files that don't load up in drawview. I've attached them as [broke_files.zip](https://github.com/martenjj/drawview/files/8049666/broke_files.zip)

I'm not sure if they are corrupted, or if it's just a format/variant that drawview doesn't support.

**Comment by martenjj** [comment]
Thanks for the report and the archive of example files.  Sorry, but most of the files appear to be corrupted.  They start off valid, but then are either truncated or have extra data appended after the end of file - sometimes even looking like a new Draw file.  This confuses the reader because in most cases the last object is truncated.

Acorn Draw and OpenVector both also fail to load these files.  The only files that they accept but DrawView rejected were "19_bin" and "beaker03".  This exposed a bug in DrawView where a font table object containing no font definitions was considered to be an error, but it should not be.  Fixed by 988664f9 and DrawView now accepts these files.

If the other files are valuable then you may be able to recover them by truncating them after the intended end of file.  For example, truncating "misc__15" to 1344 bytes long allows it to load.  You need a hex editor and a definition of the Draw file structure to find out where the real end of file should be (it is only necessary to consider top level objects).

I'm closing this report because there doesn't seem to be any automatic way of fixing the files or ignoring the corruption, apart from the font table size bug.

**Comment by Sembiance** [comment]
Thanks so much for looking into this and I'm glad to hear that the files at least revealed a bug that could be fixed. These files are not important, I just thought they may have been of some use if they weren't corrupt, but they are :)

Thanks for making this program!
